version: '2.1'
services:
  rabbitmq:
    image: rabbitmq:3-management
    restart: always
    ports:
      - 15672:15672
      - 5672:5672

  config:
    image: config:latest
    restart: always
    ports:
      - 8888:8888
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8888/actuator/health"]
      interval: 5s
      timeout: 5s
      retries: 5

  eureka:
    image: eureka:latest
    restart: always
    ports:
      - 8761:8761
    depends_on:
      config:
        condition: service_healthy
  
  gateway:
    image: gateway:latest
    restart: always
    ports:
      - 8081:8081
    depends_on:
      config:
        condition: service_healthy

  mysql:
    image: mysql:5.7.22
    environment:
      - MYSQL_DATABASE=MCC_DB
      - MYSQL_USER=MCC_USER
      - MYSQL_PASSWORD=MCC_PASSWORD
      - MYSQL_ROOT_PASSWORD=MCC_PASSWORD
    volumes:
      - ./data/mysqldb/conf:/etc/mysql/conf.d
      - ./data/mysqldb/data:/var/lib/mysql
    privileged: true
    ports:
      - "3306:3306"
    healthcheck:
      test: "/usr/bin/mysql --user=MCC_USER --password=MCC_PASSWORD --execute \"SHOW DATABASES;\""
      interval: 5s
      timeout: 5s
      retries: 5 
